name: design-template
static_sites:
  - name: design-template
    git:
      repo_clone_url: https://github.com/digitalocean/design-template.git
      branch: main
    build_command: npm run build
    output_dir: dist
    source_dir: /
    environment_slug: node-js
